title: HasuraHandler
email: me@kaz.codes
description: >-
  HasuraHandler is a Rails framework that makes building microservices for
  Hasura easy. HasuraHandler also simplifies adding Hasura to an existing
  Rails stack.
baseurl: /HasuraHandler
url: https://kazw.github.io
twitter_username:
github_username:  KazW

theme: just-the-docs
plugins:
  - jekyll-feed

color_scheme: dark

aux_links:
  "HasuraHandler on GitHub":
    - "https://github.com/KazW/HasuraHandler"

footer_content: "&copy; 2020 Kaz Walker. Distributed under the <a href=\"https://github.com/KazW/HasuraHandler/tree/master/MIT-LICENSE\">MIT license.</a>"
