name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            docs/vendor/bundle
            docs/.jekyll-cache
          key: ${{ runner.os }}-docs-gems-${{ hashFiles('docs/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-docs-gems-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install Jekyll
        working-directory: docs
        run: bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Build
        working-directory: docs
        run: bundle exec jekyll build

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
