name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: docs/vendor/bundle
          key: gems-${{ hashFiles('docs/Gemfile.lock') }}
          restore-keys: |
            doc-gems-${{ github.ref }}
            doc-gems

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build docs
        working-directory: docs
        run: |
          bundle install
          bundle exec just-the-docs rake search:init
          bundle exec jekyll build

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/_site
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
