name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: |
            docs/vendor/bundle
            docs/.jekyll-cache
            docs/.jekyll-metadata
          key: doc-gems-${{ hashFiles('docs/Gemfile.lock') }}
          restore-keys: |
            doc-gems-${{ github.ref }}
            doc-gems

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install Jekyll
        working-directory: docs
        run: bundle install --deployment

      - name: Build docs
        working-directory: docs
        run: bundle exec jekyll build --incremental

      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
