name: tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            gems-${{ github.ref }}
            gems

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bin/rails test
