name: tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: -gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            -gems-${{ github.ref }}
            -gems

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies
        run: bundle install --deployment

      - name: Run tests and send coverage report to CodeClimate
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          COVERAGE: 'true'
          CC_TEST_REPORTER_ID: ${{ secrets.CC_REPORTER_ID }}
        with:
          coverageCommand: bin/rails test
